ignored:
  - DL3006 # Always tag the version of an image explicitly
  - DL3007 # Using latest is prone to errors
  - DL3008 # Pin versions in apt get install
  - DL3013 # Pin versions in pip
  - DL3016 # Pin versions in npm
  - DL3018 # Pin versions in apk add
  - DL3033 # Specify version with yum install
  - DL3041 # Specify version with dnf install
  - DL3003 # Use WORKDIR to switch to a directory
