[main]
keepcache=0
debuglevel=2
logfile=/var/log/yum.log
exactarch=1
cachedir=/tmp/tmp_rocky10_repo_docker_build
obsoletes=1
gpgcheck=1
plugins=1
installonly_limit=3
reposdir=/dev/null
plugins=0

[BaseOS]
name=Rocky-10 - BaseOS
baseurl=https://dl.rockylinux.org/pub/rocky/10/BaseOS/$basearch/os/
gpgcheck=0
enabled=1

[AppStream]
name=Rocky-10 - AppStream
baseurl=https://dl.rockylinux.org/pub/rocky/10/AppStream/$basearch/os/
gpgcheck=0
enabled=1
