name: Bi-Monthly Refresh Images

on:
  schedule:
    - cron: '0 2 5 * *' # Runs every 5th of the month at 02:00 (UTC)
    - cron: '0 2 20 * *' # Runs every 20th of the month at 02:00 (UTC)
  workflow_dispatch: # Allows manual trigger

jobs:

  update-dockerfiles-and-artifacts:
    # Allows the job to commit changes to the repository
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

    # This application is private application of SourceMation, installed in/for
    # this repository

      - name: Get short lived token for GH APP
        id: get_autocommit_app_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APP_ID }}
          application_private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.get_autocommit_app_token.outputs.token }}
          ref: ${{ github.head_ref }}
          fetch-tags: true
          fetch-depth: 0

      - name: Update the images Dockerfiles and other artifacts
        run: |
          cd containers
          ./update-dockerfile.sh

      - name: Get current date
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - uses: stefanzweifel/git-auto-commit-action@v6
        name: Commit changes
        id: commit
        with:
          commit_message: "Update the Dockerfiles and other artifacts - ${{ env.CURRENT_DATE }}"
          tagging_message: ${{ steps.commit_tag.outputs.commit_tag }}

  generate-build-order:
    needs: update-dockerfiles-and-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-tags: true
          fetch-depth: 0
      - name: Generate build order
        run: |
          cd containers
          ./docker-build-order.py images/ sourcemation

      - name: Upload build order
        uses: actions/upload-artifact@v4
        with:
          name: build_order
          path: containers/build_order.txt

  build-containers:
    needs: generate-build-order
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build order
        uses: actions/download-artifact@v4
        with:
          name: build_order

      - name: Build containers
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          string=$(cat build_order.txt | tr '\n' ',' | sed 's/,$//')
          container=$(echo "$string" | cut -d',' -f1)
          to_build_list=$(echo "$string" | cut -d',' -f2-)

          echo "Container to build: $container"
          echo "Next container to build: $to_build_list"
          echo "Building container: $container"
          gh workflow run build-manual.yml  --repo SourceMation/images -f container_name=$container  -f next_containers="$to_build_list"
