name: Bi-Monthly Refresh Images

on:
  schedule:
    - cron: '0 7 5 * *' # Runs every 5th of the month at 07:00 (UTC)
    - cron: '0 7 20 * *' # Runs every 20th of the month at 07:00 (UTC)
  workflow_dispatch: # Allows manual trigger

jobs:

  update-dockerfiles-and-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-tags: true
          fetch-depth: 0

      - name: Update the images Dockerfiles and other artifacts
        run: |
          cd containers
          ./update-dockerfile.sh

      - name: Get current date
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - uses: stefanzweifel/git-auto-commit-action@v5
        name: Commit changes
        id: commit
        with:
          commit_message: "Update the Dockerfiles and other artifacts - ${{ env.CURRENT_DATE }}"
          tagging_message: ${{ steps.commit_tag.outputs.commit_tag }}

  generate-build-order:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-tags: true
          fetch-depth: 0

# Temporary disabled
      #- name: Generate build order
        #run: |
          #cd containers
          #./docker-build-order.py images/ sourcemation

      #- name: Upload build order
        #uses: actions/upload-artifact@v4
        #with:
          #name: build_order
          #path: containers/build_order.txt

  #build-containers:
    #needs: generate-build-order
    #runs-on: ubuntu-latest
    #steps:
      #- name: Checkout repository
        #uses: actions/checkout@v2

      #- name: Download build order
        #uses: actions/download-artifact@v4
        #with:
          #name: build_order

      #- name: Build containers
        #env:
          #GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        #run: |
          #string=$(cat build_order.txt | tr '\n' ',' | sed 's/,$//')
          #container=$(echo "$string" | cut -d',' -f1)
          #to_build_list=$(echo "$string" | cut -d',' -f2-)

          #echo "Container to build: $container"
          #echo "Next container to build: $to_build_list"
          #echo "Building container: $container"
          #gh workflow run build-manual.yml  --repo SourceMation/images -f container_name=$container  -f next_containers="$to_build_list"
