name: Build container
run-name: Manual build of ${{ inputs.container_name }} container by @${{ github.actor }}

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      container_name:
        description: 'Name of the container to build'
        default: 'jenkins'
        required: true
        type: string
      push_image:
        description: 'Push the image to the registries'
        default: true
        required: false
        type: boolean
      test_image:
        description: 'Test the image - note that this will only work if the image is a testable image with tests provided!'
        default: true
        required: false
        type: boolean



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build_container:
    env:
      QUAY_USER: ${{ secrets.QUAY_USER }}
      QUAY_PASS: ${{ secrets.QUAY_PASS }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      PUSH_IMAGE: ${{ inputs.push_image }}
      TEST_IMAGE: ${{ inputs.test_image }}
      APIKEY__QUAY_IO: ${{ secrets.QUAY_API }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # LOL - this is required to use files from the repository
    - uses: actions/checkout@v4
    - name: Install prerequisites - docker
      run: |
          sudo apt-get update
          sudo apt-get install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin dnf
          sudo usermod -aG docker $USER
          sudo systemctl enable --now docker
    # run container build script that is located in the repository
    - name: Build the container, test, push and push readme
      run: |
        pwd
        bash build-container.sh ${{ inputs.container_name }}
