name: Monthly Refresh Images

on:
# schedule:
#   - cron: '0 8 * * 1' # Runs at 08:00 on the first Monday of the month
  workflow_dispatch: # Allows manual trigger

jobs:
  generate-build-order:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate build order
        run: |
          cd containers
          chmod +x ./docker-build-order.py
          ./docker-build-order.py images/ sourcemation

      - name: Upload build order
        uses: actions/upload-artifact@v4
        with:
          name: build_order
          path: containers/build_order.txt

  build-containers:
    needs: generate-build-order
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build order
        uses: actions/download-artifact@v4
        with:
          name: build_order

      - name: Build containers
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          for container in $(cat build_order.txt); do
            echo "Building container: $container"
            gh workflow run build-manual.yml -f container_name=$container --repo SourceMation/images
          done
